# cargo-release configuration
# https://github.com/crate-ci/cargo-release

consolidate-commits = true
sign-commit = false
sign-tag = false
tag-prefix = ""
publish = false

pre-release-commit-message = "chore: release {{version}}"
tag-message = "release {{version}}"
